version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/2024-October-VCT-Hackathon/
hooks:
  BeforeInstall:
    - location: scripts/set_permissions.sh
      timeout: 30
      runas: root
    - location: scripts/before_install.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root